name: 'GitHub Workflow Alert'

inputs:
  webhook_url: 
    description: "chat space url"
    type: 'string'
    required: true
  mention:
    description: "mention people or not, format <users/user_id>"
    type: 'string'
    default: '<users/all>'
    required: false

jobs:
  using: 'composite'
  steps:
    - uses: 'actions/checkout@v1'
    - name: 'test'
      run: |
        echo ${{inputs.webhook_url}}
    # - name: 'Send error message'
      # run: |
      #   # curl -H "Content-Type: application/json" -X POST  "${{inputs.webhook_url}}" --data '{"text": "${{inputs.mention}} Repo: https://github.com/${{ github.repository }} had a failing action at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}} and more words and stuff"}'
      #   curl -H "Content-Type: application/json" -X POST  "${{inputs.webhook_url}}" --data '{ 
      #     "text": "<users/all>",
      #     "cardsV2": [
      #       {
      #         "cardId": "avatarCard", 
      #         "card": {
      #           "name": "Avatar Card", 
      #           "header": {
      #             "title": "Hello ${{ github.triggering_actor }}!"
      #           }, 
      #           "sections": [ 
      #             {
      #               "widgets": [
      #                 { 
      #                   "textParagraph": { 
      #                     "text": "Repo: https://github.com/${{ github.repository }} had a failing action at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}} and more words and stuff"
      #                   }
      #                 },
      #                 {
      #                   "decoratedText": {
      #                     "startIcon": {
      #                       "knownIcon": "TICKET",
      #                     },
      #                     "text": "<font color=\"#FF0000\">Failed</font>",
      #                   },
      #                 },
      #                 { 
      #                   "image": { 
      #                     "imageUrl": "https://media.tenor.com/W_iAZy_edGAAAAAC/patrick-star.gif" 
      #                   }
      #                 },
      #                 {
      #                   "buttonList": {
      #                     "buttons" : [
      #                       {
      #                         "text": "Go to job",
      #                         "onClick": {
      #                           "openLink": {
      #                             "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}}",
      #                           }
      #                         }
      #                       },
      #                     ]
      #                   }
      #                 }
      #               ]
      #             }
      #           ]
      #         }
      #       }
      #     ]
      #   }'

