name: "My failing workflow with CLI"

on:
  workflow_dispatch:
    inputs:
      fail_intentionally:
        type: boolean
        default: true
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - name: Go build
        run: go build -v ./...
      - name: "Fake intentional failing step"
        run: exit 1
      - name: Report if failed
        if: always()
        run: ./hackathon chat workflownotification --webhook_url=${{ secrets.webhook_url }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_CONTEXT: ${{ toJson(job) }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
          RUNNER_CONTEXT: ${{ toJson(runner) }}
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
