name: "My failing workflow with CLI"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - name: Go build
        run: go build -v ./...
      - name: "Fake intentional failing step"
        run: exit 1
      - name: Report if failed
        if: failure()
        # TODO: pull these values from repo variables
        run: ./hackathon workflow-tool chat -space=AAAAUJgrNvE -key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI -token=VyyAuvWCmbwWkXtytXxNIc5R_xX41_fi4WxieHsSggs%3D
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_CONTEXT: ${{ toJson(job) }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
          RUNNER_CONTEXT: ${{ toJson(runner) }}
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
