name: "My failing workflow with CLI"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - name: Go build
        run: go build -v ./...
      - name: "Fake intentional failing step"
        run: exit 1
      - name: Report if failed
        if: failure()
        run: ./hackathon chat workflownotification -space=${{ vars.CHAT_SPACE }} -key=${{ secrets.CHAT_KEY }} -token=${{ secrets.CHAT_TOKEN }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_CONTEXT: ${{ toJson(job) }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
          RUNNER_CONTEXT: ${{ toJson(runner) }}
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
