name: "My flaky workflow"

on:
  workflow_dispatch:
    inputs:
      fail_intentionally:
        type: boolean
        default: true
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Fake intentional failing step"
        if: ${{ inputs.fail_intentionally }}
        run: exit 1
      - name: 'Report status to chat'
        if: always()
        uses: 'drevell/hackathon-action@v12'
        with:
          webhook_url: '${{ vars.WEBHOOK_URL }}'
