name: 'send-message'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  url: ${{secrets.WEBHOOK_URL}}

jobs:
  snapshot:
    uses: './.github/workflows/sample.yml'
    with:
      webhook_url: $url
      message: 'hello word'
      mention: "<users/all>"
