name: 'send-message'

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - 'main'
  #pull_request:
  #  branches:
  #    - 'main'

jobs:
  snapshot:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3' # ratchet:actions/checkout@v3
      - name: 'Alert' 
        uses: 'drevell/hackathon-action@v7'
        with:
          webhook_url: '${{ secrets.WEBHOOK_URL }}'
          mention: "<users/all>"
          chat_space: '${{vars.CHAT_SPACE}}'
          chat_key:   ${{secrets.CHAT_KEY}}
          chat_token: ${{secrets.CHAT_TOKEN}}
          github_token: ${{github.token}}