name: 'release'
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: 'write'
  packages: 'write'
jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b' # ratchet:actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: 'actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a' # ratchet:actions/setup-go@v3
        with:
          go-version: '1.18'
      - uses: 'goreleaser/goreleaser-action@b953231f81b8dfd023c58e0854a721e35037f28b' # ratchet:goreleaser/goreleaser-action@v2
        with:
          version: 'latest'
          args: 'release --clean'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'