name: 'sample'
on:
  workflow_call:
    inputs:
      mention:
        description: "mention people or not, format <users/user_id>"
        type: 'string'
        default: '<users/all>'
        required: false

jobs:
  checkout:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v1'
      - name: 'Send error message'
        run: |
          curl -H "Content-Type: application/json" -X POST  "${{secrets.WEBHOOK_URL}}" --data '{"text": "${{inputs.mention}} Repo: https://github.com/${{ github.repository }} had a failing action at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}} and more words and stuff"}'
