name: 'sample'
on:
  workflow_call:
    inputs:
      mention:
        description: "mention people or not, format <users/user_id>"
        type: 'string'
        default: '<users/all>'
        required: false

jobs:
  checkout:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v1'
      - name: 'Send error message'
        run: |
          # curl -H "Content-Type: application/json" -X POST  "${{secrets.WEBHOOK_URL}}" --data '{"text": "${{inputs.mention}} Repo: https://github.com/${{ github.repository }} had a failing action at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}} and more words and stuff"}'
          curl -H "Content-Type: application/json" -X POST  "${{secrets.WEBHOOK_URL}}" --data '{ 
            "cardsV2": [
              {
                "cardId": "avatarCard", 
                "card": {
                  "name": "Avatar Card", 
                  "header": {
                    "title": "Hello Dave!"
                  }, 
                  "sections": [ 
                    {
                      "widgets": [
                        { 
                          "textParagraph": { 
                            "text": "Repo: https://github.com/${{ github.repository }} had a failing action at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}} and more words and stuff"
                          }
                        },
                        { 
                          "image": { 
                            "imageUrl": "https://media.tenor.com/W_iAZy_edGAAAAAC/patrick-star.gif" 
                          }
                        }
                      ]
                    }
                  ]
                }
              }
            ]
          }'

    # {"cardsV2": [{"cardId": "avatarCard", "card": {"name": "Avatar Card", "header": {"title": "Hello Dave!"}}}]}


    # -d '{"login":"my_login","password":"my_password"}'
    # {"cardsV"}

# curl -H "Content-Type: application/json" -X POST  "https://chat.googleapis.com/v1/spaces/AAAAUJgrNvE/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=VyyAuvWCmbwWkXtytXxNIc5R_xX41_fi4WxieHsSggs%3D" --data \
# '{ 
#   "cardsV2": [
#     {
#       "cardId": "avatarCard", 
#       "card": {
#         "name": "Avatar Card", 
#         "header": {
#           "title": "Hello Dave!"
#         }, 
#         "sections": [ 
#           {
#             "widgets": [
#               { 
#                 "textParagraph": { 
#                   "text": "Repo: https://github.com/${{ github.repository }} had a failing action at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}} and more words and stuff"
#                 }
#               },
#               { 
#                 "image": { 
#                   "imageUrl": "https://media.tenor.com/W_iAZy_edGAAAAAC/patrick-star.gif" 
#                 }
#               }
#             ]
#           }
#         ]
#       }
#     }
#   ]
# }'