name: 'sample'
on:
  workflow_call:
    inputs:
      message:
        description: 'Message to be sent'
        type: 'string'
        required: true
      mention:
        description: "mention people or not, format <users/user_id>"
        type: 'string'
        required: true

jobs:
  checkout:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v1'
      - name: 'Send error message'
        run: |
          curl -H "Content-Type: application/json" -X POST  "${{secrets.WEBHOOK_URL}}" --data '{"text": "${{inputs.mention}} ${{inputs.message}}"}'
